# Generated by Django 2.2.1 on 2019-05-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('discipline', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('phone', models.IntegerField(default=0)),
                ('interview_offer', models.BooleanField(default=None, null=True)),
                ('project_name', models.CharField(max_length=200)),
            ],
        ),
    ]
