# Generated by Django 2.2.1 on 2019-05-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_display', '0002_auto_20190331_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotForProfits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfp_name', models.CharField(max_length=200)),
                ('years_w_veep', models.FloatField()),
                ('num_projects', models.IntegerField()),
                ('num_projects_completed', models.IntegerField()),
                ('primary_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('completion_rate', models.FloatField(max_length=200)),
                ('project_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('num_members', models.IntegerField()),
                ('avg_yos', models.FloatField()),
                ('most_common_discipline', models.CharField(max_length=200)),
            ],
        ),
    ]
