# Generated by Django 2.2.1 on 2019-08-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_display', '0003_notforprofits_projects_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='discipline',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='interview_offer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(default=-1, max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='project_name',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='students',
            name='year',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
