# Generated by Django 2.1.5 on 2019-03-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('discipline', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('phone', models.IntegerField(default=0)),
                ('interview_offer', models.BooleanField(default=None, null=True)),
                ('project_name', models.CharField(max_length=200)),
            ],
        ),
    ]
