# Generated by Django 2.1.5 on 2019-03-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datadisplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
